[package]
name = "es_percolator"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
fundsp = "0.23.0"
nalgebra = "0.35.0"
nice-plug = "0.4"

# # Enable a small amount of optimization in the dev profile.
# [profile.dev]
# opt-level = 1
#
# # Enable more optimization in the release profile at the cost of compile time.
# [profile.release]
# codegen-units = 1
# lto = "thin"
# # (optional) helps reduce binary size
# strip = "symbols"
#
# [profile.profiling]
# inherits = "release"
# debug = true
# strip = "none"
